apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
patchesStrategicMerge:
  - service.yaml
  - deployment.yaml
images:
  - name: quay.io/cybozu/argocd
    newTag: 2.10.2.2
  - name: quay.io/cybozu/dex
    newTag: 2.37.0.2
  - name: quay.io/cybozu/redis
    newTag: 7.0.11.2
  - name: ghcr.io/cybozu/haproxy
    newTag: 2.6.14.2
