apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anyapps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/kmdkuk/argocd-image-updater-test:1.x-0
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    # https://argocd-image-updater.readthedocs.io/en/stable/configuration/images/#ignoring-certain-tags
    # if you want to disable updating an image temporarily
    # argocd-image-updater.argoproj.io/app.ignore-tags: "*"
spec:
  project: default
  source:
    repoURL: https://github.com/kmdkuk/argocd-test.git
    path: anyapps/base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
