apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/cert-manager.yaml
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: quay.io/cybozu/cert-manager
    newTag: 1.13.2.2
