apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  git.commit-message-template: |
    build: automatic update of {{ .AppName }}

    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
  git.user: cybozu-neco
  git.email: neco@cybozu.com
