apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  template:
    spec:
      containers:
        - name: argocd-image-updater
          image: argocd-image-updater:latest
          imagePullPolicy: IfNotPresent
