apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  template:
    spec:
      containers:
        - name: argocd-image-updater
          image: ghcr.io/cybozu/argocd-image-updater:0.12.2.1
          imagePullPolicy: IfNotPresent
