apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
namespace: argocd
patchesStrategicMerge:
  - configmap.yaml
images:
  - name: quay.io/argoprojlabs/argocd-image-updater
    newName: argocd-image-updater
    newTag: latest
