name: create image updater pull request
on:
  push:
    branches:
      - 'image-updater/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --fill --base=main --head=${{ github.ref_name }}
  close-older-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get old PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repository=$(echo ${{ github.ref_name }} | awk -F '/' '{print $2}')
          image_name=$(echo ${{ github.ref_name }} | awk -F '/' '{print $3}')
          pr_number=$(gh pr list \
            --state open \
            --json number,headRefName \
            --jq ".[] |[.number, .headRefName]|@csv" \
            | awk -F, '{print $1,$2}' \
            | sed -e 's/"//g' \
            | grep "image-updater/${repository}/${image_name}" \
            | grep -v "${{ github.ref_name }}" \
            | awk '{print $1})
          for num in ${pr_number}; do
            gh pr close -d -c "new PR branch: #$(gh pr view ${{ github.ref_name }} --json number --jq .number)" $num
          done
