name: Docker build and push
on:
  push:
    branches-ignore:
      - 'image-updater/**'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Decide tag name
        run: |
          echo "TAG=$(cat image/TAG)-$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - run: |
          sed -i s/TAG/${{ env.TAG }}/g image/index.html
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: image
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/argocd-image-updater-test:${{ env.TAG }}
